version: 0.1
phases:
  install:
    commands:
      - mvn package
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambdabucket-1
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: jar
  files:
    - target/LambdaTest-1.0-SNAPSHOT.jar
    - NewSamTemplate.yaml