AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handle users
Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.infosupport.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/LambdaTest-1.0-SNAPSHOT.jar
